// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daghobrbxgkgmflkcnyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZ2hvYnJieGdrZ21mbGtjbnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMjQ3MzAsImV4cCI6MjA3NTgwMDczMH0.ecYFGuWBhTwoMPUg0I6DCMua8WiL4K1gpV3u5gwrOdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});